services:
  database:
    image: postgres:17-alpine
#   # Exposing the database may be useful only for local development.
#   # To expose it (why?), create a Docker Compose override file.
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:8-alpine
#   # Exposing Redis may be useful only for local development.
#   # To expose it (why?), create a Docker Compose override file.
#    ports:
#      - "6379:6379"
    networks:
      - backend

  pretix:
    image: pretix/standalone:stable
    depends_on:
      - database
      - redis
    ports:
      - "$PRETIX_LISTEN:80"
    volumes:
      - ./data/postfix/etc/pretix.cfg:/etc/pretix/pretix.cfg
      - pretix_data:/data
    networks:
      - backend

volumes:
  pretix_data:
  postgres_data:
  pretix_src:

networks:
  backend:
